// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddBulletinandMessageDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddBulletinandMessageDB));
        
        string IMigrationMetadata.Id
        {
            get { return "202405060436291_Add-Bulletin-and-Message-DB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
