// <auto-generated />
namespace WebApplication1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddMemberDBNewColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMemberDBNewColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "202405190857084_Add-Member-DB-New-Columns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
